"""create stats models

Revision ID: e99ed2b6b738
Revises: 48d42dca0b05
Create Date: 2023-04-22 23:26:26.000692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99ed2b6b738'
down_revision = '48d42dca0b05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('remote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seniority',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('seniority', sa.String(length=20), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seniority')
    op.drop_table('positions')
    op.drop_table('localization')
    # ### end Alembic commands ###
